# Enable logging over UART with all the bells and whistles in deferred mode
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=n
CONFIG_PRINTK=y
CONFIG_SERIAL=y
CONFIG_TIMEOUT_64BIT=y # required for deferred tasks
